### ISSUE TITLE
Define datetime model in yaml

### ISSUE THREAD

**Issue by not7cd** [hs3city/inf_event_cli#13]
Proponuję luźną interpretację [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601).
Nie znam stanowiska co do stref czasowych, ale nie uważam tego za konieczność w sytuacji w której wszyscy operujemy na czasie lokalnym. Czasy podawane bez `TZD` powinny zostać uznane za lokalne #9.
```yaml
---
name: event
datetime: YYYY-MM-DDThh:mmTZD/PTnH # Czas i data wydarzenia, wydarzenie trwa n godzin
```
```yaml
--- # Podzielone w datetime, można o coś jeszcze rozszerzyć
name: event
datetime: 
    date: YYYY-MM-DD
    time: hh:mmTZD
    duration: PThhHmmM # w pythonie jako 'deltatime'
```
Można się nieco pokłócić jak zapisywać miejsce w czasie wydarzeń w HS. Sam ISO 8601 może sobie z tym bardzo dobrze poradzić, ale należy też zadbać o czytelność i dostępność (w sumie wysyłanie zgłoszeń w formacie yaml wyklucza 90% społeczeństwa).

**Comment by not7cd** [comment]
```yaml
---
name: "Python Hacking"
datetime: 2017-08-16T18:00/P3H # 16.08 o godzinie 18:00 przez 3 godziny
repeat: R4/P2W # Spotkanie cykliczne, 4 spotkania co 2 tygodnie
```
Inna propozycja zapisu

**Comment by allgreed** [comment]
Odnośnie czasu trwania -> rzeczywiście to by się przydało, ale definitywnie rozdrobnione

Jeśli chodzi o tworzenie wydarzeń cyklicznych -> jeżeli chciałbyś taką funkcjonalność to plox osobne issue ;)

Ostatecznie coś takiego byłoby spoko:

```yaml
[...]
datetime: 
    start: YYYY-MM-DD hh:mm:ss
    duration: hh:mm:ss
```

Moment rozpoczęcia fajnie jakby został w jednym kawałku, bo parser YAMLa od razu robi z tego datetime ;)

@not7cd Chciałbyś się podjąć implementacji?
